<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PH.DbAppSettings.Example.MinimalApi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PH.DbAppSettings.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PH.DbAppSettings\PH.DbAppSettings.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.*-*" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.*-*" />
  </ItemGroup>

</Project>
